apiVersion: apps/v1
kind: {{ .Values.deploymentType }}
metadata:
  name: {{ include "mattermost-rtcd.fullname" . }}
  labels:
    {{- include "mattermost-rtcd.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mattermost-rtcd.selectorLabels" . | nindent 6 }}
  {{- if eq .Values.deploymentType "Deployment" }}
  strategy:
  {{- else }}
  updateStrategy:
  {{- end }}
    {{- if eq .Values.Configuration.updateStrategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.Configuration.maxUnavailable }}
    {{- end }}
    type: {{ .Values.Configuration.updateStrategy }}
  {{- if eq .Values.deploymentType "Deployment" }}
  replicas: {{ .Values.Configuration.replicas | default 1 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mattermost-rtcd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.Configuration.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      {{- end }}
      serviceAccountName: {{ include "mattermost-rtcd.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.Configuration.terminationGracePeriod }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.Configuration.environmentVariables }}
          env:
            {{- range $key, $val := .Values.Configuration.environmentVariables }}
            - name: {{ $key }}
              value: {{ $val }}
            {{- end}}
          {{- end }}
          {{- if .Values.Configuration.extraVolumeMounts }}
          volumeMounts: {{ toYaml .Values.Configuration.extraVolumeMounts | nindent 12 }}
          {{- end }}
          ports:
            - name: api
              containerPort: {{ .Values.service.apiPort.port }}
              {{- if .Values.Configuration.hostNetwork }}
              hostPort: {{ .Values.service.apiPort.port }}
              {{- end }}
              protocol: TCP              
            - name: rtc
              containerPort: {{ .Values.service.rtcPort.port }}
              {{- if .Values.Configuration.hostNetwork }}
              hostPort: {{ .Values.service.rtcPort.port }}
              {{- end }}
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /version
              port: api
          readinessProbe:
            httpGet:
              path: /version
              port: api
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.Configuration.extraVolumes }}
      volumes: {{ toYaml .Values.Configuration.extraVolumes | nindent 8 }}
      {{- end }}
