apiVersion: v1
kind: Service
metadata:
  name: {{ include "mattermost-rtcd.fullname" . }}
  labels:
    {{- include "mattermost-rtcd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "ClusterIP" }}
  clusterIP: {{ .Values.service.ClusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.apiPort.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.apiPort.nodePort }}
      {{- end }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.rtcPort.port }}
      targetPort: rtc
      protocol: UDP
      name: rtc
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.rtcPort.NodePort  }}
      {{- end }}
  selector:
    {{- include "mattermost-rtcd.selectorLabels" . | nindent 4 }}
